#!/usr/bin/env bash

register_workspace_setting 'dev'

function set_workspace_settings_to_dev() {
  export VAGRANT_DEFAULT_PROVIDER=virtualbox
  export VAGRANT_CONTEXT="${VAGRANT_DEFAULT_PROVIDER}/dev"

  export PATHS_PROJECT_DEPLOY_VAGRANT_CONTEXT_HOME="${PATHS_PROJECT_DEPLOY_VAGRANT_HOME}/${VAGRANT_CONTEXT}"
  export PATHS_PROJECT_DEPLOY_VAGRANT_STATE="${PATHS_PROJECT_DEPLOY_VAGRANT_CONTEXT_HOME}/.vagrant"
  export PATHS_PROJECT_DEPLOY_VAGRANT_CONTEXT_VAGRANTFILE="${PATHS_PROJECT_DEPLOY_VAGRANT_CONTEXT_HOME}/Vagrantfile"

  export VAGRANT_VAGRANTFILE="${PATHS_PROJECT_DEPLOY_VAGRANT_CONTEXT_VAGRANTFILE}"


  export TEST_TYPES=dev:acceptance
  export HATS=dev
}
