- hosts: localhost
  connection: local
  tasks:
    - name: Install VirtualBox
      homebrew_cask: name=virtualbox state=present
    - name: Install Vagrant
      homebrew_cask: name=vagrant state=present
