require "#{ENV['PATHS_PROJECT_DEPLOY_VAGRANT_LIB']}/common.rb"
require 'fileutils'

Vagrant.configure('2') do |master_config|

  master_config.vm.define :windows_box do |config|
    config.vm.box = 'gusztavvargadr/w16s-vs17p'
    config.vm.network 'private_network', ip: '10.11.12.101'

    config.vm.communicator = 'winrm'
    config.vm.guest = :windows
    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
    config.winrm.password = 'vagrant'

    config.vm.provider 'virtualbox' do |v|
      v.linked_clone = true
    end

    config.vm.provision 'ansible' do |ansible|
      ansible.verbose = 'vvvvv'
      ansible.playbook = File.expand_path('playbooks/windows.yml', File.dirname(__FILE__))

      ansible.host_vars = {
        web: {
          ansible_host: '10.11.12.101',
          ansible_port: 5985,
          ansible_winrm_scheme: 'http',
          ansible_winrm_server_cert_validation: 'ignore'
        }
      }
    end
  end

  master_config.vm.define :centos_box do |config|
    config.vm.box = 'centos/6'
    config.vm.network 'private_network', ip: '10.11.12.102'

    config.vm.provider 'virtualbox' do |v|
      v.linked_clone = true
    end

    config.vm.provision 'ansible' do |ansible|
      ansible.verbose = 'vvvvv'

      ansible.become = true
      ansible.become_user = 'root'

      ansible.galaxy_role_file = File.expand_path('playbooks/requirements.yml', File.dirname(__FILE__))
      ansible.galaxy_roles_path = ENV['PATHS_ORGANIZATION_ANSIBLE_GALAXY_HOME']
      ansible.playbook = File.expand_path('playbooks/centos.yml', File.dirname(__FILE__))

      # raise ansible.galaxy_roles_path unless File.exist?(ansible.galaxy_roles_path)
      FileUtils.mkdir_p ansible.galaxy_roles_path unless File.exist?(ansible.galaxy_roles_path)
    end
  end
end
